# -*- coding: utf-8 -*-
from . import account_invoice
from . import  pricelist_item
from . import service_base
from . import asociados_al_servicio
from . import invoice_type
from . import service_type
from . import product
from . import default_expenses
from . import res_partner
from . import vehiculo
from . import service_products
from . import service_carga
from . import tarifario
from . import servicio_base_template
from . import fronteras
from . import depositos
from . import service_products_to_calendar
from . import catalogo_bultos
